routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'PageController@homepage')->name('homepage');
Route::get('/contact-us', 'ContactController@form')->name('inquiry.form');
Route::post('/contact-us', 'ContactController@send')
    ->middleware('throttle:5')
    ->name('inquiry.send');

Route::get('/blog', 'PageController@blog')->name('blog.index');
Route::get('/blog/{post}', 'PageController@post')->name('blog.post');
Route::get('{page}', 'PageController@single')->name('single');

Route::prefix(config('admin.url'))->group(function () {
    Auth::routes();
    Route::middleware('auth')->group(function () {
        Route::get('/home', 'Admin\HomeController@index')->name('home');
        Route::resource('/posts', 'Admin\PostController');
        Route::resource('/pages', 'Admin\PageController');
        Route::resource('/menus', 'Admin\MenuController');
    });
});

resources/views/admin/page/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col-md-12 mb-2">
        <a class="btn btn-secondary col-md-2" href="{{route('pages.index')}}">{{__('Back')}}</a>
    </div>
</div>
<div class="card">
    <div class="card-header">{{__('Create Page')}}</div>

    <div class="card-body">
        <form action="{{route('pages.store')}}" method="post">
            @csrf
            <div class="form-group">
                <label for="title">{{__('Title')}}</label>
                <input type="text" class="form-control" id="title" name="title"
                    placeholder="ex: {{__('title page')}}"
                    value="{{ old('title') }}">
                @include('admin.components.error', ['errors' => $errors->get('title')])
            </div>
            <div class="form-group">
                <label for="{{__('slug')}}">{{__('Slug')}}</label>
                <input type="text" class="form-control" id="slug" name="slug"
                    placeholder="ex: {{__('slug-page')}}"
                    value="{{ old('slug') }}">
                @include('admin.components.error', ['errors' => $errors->get('slug')])
            </div>
            <div class="form-group">
                <label for="contents">{{__('Content')}}</label>
                @include('admin.components.error', ['errors' => $errors->get('content')])
                <textarea class="form-control init-tinymce" id="contents" name="content" rows="3">
                    {{old('content')}}
                </textarea>
            </div>

            <button type="submit" class="btn btn-primary">{{__('Submit')}}</button>
        </form>
    </div>
</div>
@endsection

@section('scripts')
@component('admin.components.scripts', [
    'loads' => [
        asset('/vendor/tinymce/tinymce.min.js'),
        asset('/js/admin/inittinymce.js'),
    ]
])
@endcomponent
@endsection

resources/views/admin/page/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col-md-12 mb-2">
        <a class="btn btn-secondary col-md-2" href="{{route('pages.index')}}">{{__('Back')}}</a>
    </div>
</div>
<div class="card">

    <div class="card-header">{{__('Edit Page')}}</div>
    <div class="card-body">
        <form action="{{route('pages.update', $page->id)}}" method="post">
            @csrf
            @method('put')
            <div class="form-group">
                <label for="{{__('title')}}">{{__('Title')}}</label>
                <input type="hidden" name="id" value="{{$page->id}}">
                <input type="text" class="form-control" id="title" name="title" 
                    placeholder="ex: title page" 
                    value="{{ old('title') ?? $page->title }}">
                @include('admin.components.error', ['errors' => $errors->get('title')])
            </div>
            <div class="form-group">
                <label for="{{__('slug')}}">{{__('Slug')}}</label>
                <input type="text" class="form-control" id="slug" name="slug" 
                    placeholder="ex: slug-page"
                    value="{{ old('slug') ?? $page->slug }}">
                @include('admin.components.error', ['errors' => $errors->get('slug')])
            </div>
            <div class="form-group">
                <label for="contents">{{__('Content')}}</label>
                @include('admin.components.error', ['errors' => $errors->get('content')])
                <textarea class="form-control init-tinymce" id="contents" name="content" rows="3">
                    {{ old('content') ?? $page->content }}
                </textarea>
            </div>

            <button type="submit" class="btn btn-primary">{{__('Submit')}}</button>
        </form>
    </div>
</div>
@endsection

@section('scripts')
@component('admin.components.scripts', [
    'loads' => [
        asset('/vendor/tinymce/tinymce.min.js'),
        asset('/js/admin/inittinymce.js'),
    ]
])
@endcomponent
@endsection

resources/views/admin/page/index.blade.php
@extends('layouts.admin')

@section('content')
@include('admin.includes.alert')
<div class="row">
    <div class="col-md-12 mb-2">
        <a class="btn btn-primary col-md-2" href="{{route('pages.create')}}">{{__('Create Page')}}</a>
    </div>
</div>
<div class="card">
    <div class="card-header">{{__('Page list')}}</div>

    <div class="card-body">
         <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th class="col-8">{{(__('Page'))}}</th>
                        <th colspan=2>{{ __('Action') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($pages as $page)
                    <tr>
                        <td class="col-8"><a href="{{route('pages.show', $page->id)}}">{{ $page->title }}</a></td>
                        <td class="col-2"><a href="{{route('pages.edit', $page->id)}}">{{ __('Edit') }}</a></td>
                        <td>
                            <delete-btn data-url="{{route('pages.destroy', $page->id)}}"
                                message="{{__('Are you sure?')}}"
                                title="{{__('Delete Page')}}">
                            </delete-btn>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="3" class="text-center">{{ __('No Data') }}</td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
            {{ $pages->links() }}
        </div>
    </div>
</div>
@endsection

resources/views/admin/page/show.blade.php
@extends('layouts.admin')

@section('content')
@include('admin.includes.alert')
<div class="row">
    <div class="col-md-12 mb-2">
        <a class="btn btn-secondary col-md-2" href="{{route('pages.index')}}">{{__('Back')}}</a>
        <a class="btn btn-primary col-md-2" href="{{route('pages.edit', $page->id)}}">{{__('Edit')}}</a>
    </div>
</div>
<div class="card">
    <div class="card-header">{{__('Page Details')}}</div>
    <div class="card-body">
        <div>
            <label><b>{{__('Title')}}</b></label>
            <p>{{$page->title}}</p>
        </div>
        <div>
            <label><b>{{__('Slug')}}</b></label>
            <p>{{$page->slug}}</p>
        </div>
        <div>
            <label><b>{{__('Content')}}</b></label> 
            <div>{!!$page->content!!}</div>
        </div>
    </div>
</div>
@endsection