routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'PageController@homepage')->name('homepage');
Route::get('/contact-us', 'ContactController@form')->name('inquiry.form');
Route::post('/contact-us', 'ContactController@send')
    ->middleware('throttle:5')
    ->name('inquiry.send');

Route::get('/blog', 'PageController@blog')->name('blog.index');
Route::get('/blog/{post}', 'PageController@post')->name('blog.post');
Route::get('{page}', 'PageController@single')->name('single');

Route::prefix(config('admin.url'))->group(function () {
    Auth::routes();
    Route::middleware('auth')->group(function () {
        Route::get('/home', 'Admin\HomeController@index')->name('home');
        Route::resource('/posts', 'Admin\PostController');
        Route::resource('/pages', 'Admin\PageController');
        Route::resource('/menus', 'Admin\MenuController');
    });
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = [
        'title',
        'slug',
        'content',
        'author_id',
    ];

    public function author()
    {
        return $this->belongsTo('App\Models\User', 'author_id');
    }

    public function save(array $options = array())
    {
        $this->author_id = auth()->user()->id;
        parent::save($options);
    }
}

app/Models/PostView.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PostView extends Post
{
    protected $table = 'posts';

    public function getRouteKeyName()
    {
        return 'slug';
    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Page\UpdateRequest;
use App\Http\Requests\Admin\Post\StoreRequest;
use App\Models\Post;
use App\Traits\ReturnTrait;
use Illuminate\Http\Request;

class PostController extends Controller
{
    use ReturnTrait;

    public function index()
    {
        $posts = Post::paginate(config('admin.post.limit'));
        return view('admin.post.index', compact('posts'));
    }

    public function create()
    {
        return view('admin.post.create');
    }

    public function store(StoreRequest $request)
    {
        $post = Post::create($request->validated());
        return redirect()->route('posts.show', $post->id)
            ->with('success', __('New post has been added'));
    }

    public function show(Post $post)
    {
        return view('admin.post.show', compact('post'));
    }

    public function edit(Post $post)
    {
        return view('admin.post.edit', compact('post'));
    }

    public function update(UpdateRequest $request, Post $post)
    {
        $post->update($request->validated());
        return redirect()->route('posts.show', $post->id)
            ->with('success', __('Post has been updated'));
    }

    public function destroy(Request $request, Post $post)
    {
        $post->delete();
        if ($request->expectsJson()) {
            return $this->returnExpectJson(
                ['status' => 'ok'],
                ['success' => __('Post has been deleted')]
            );
        }
        return redirect()->route('post.index')
            ->with('success', __('Post has been deleted'));
    }
}

resources/views/admin/post/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col-md-12 mb-2">
        <a class="btn btn-secondary col-md-2" href="{{route('posts.index')}}">{{__('Back')}}</a>
    </div>
</div>
<div class="card">
    <div class="card-header">{{__('Create Post')}}</div>

    <div class="card-body">
        <form action="{{route('posts.store')}}" method="post">
            @csrf
            <div class="form-group">
                <label for="title">{{__('Title')}}</label>
                <input type="text" class="form-control" id="title" name="title" 
                    placeholder="ex: {{__('title page')}}"
                    value="{{ old('title') }}">
                @include('admin.components.error', ['errors' => $errors->get('title')])
            </div>
            <div class="form-group">
                <label for="slug">{{__('Slug')}}</label>
                <input type="text" class="form-control" id="slug" name="slug" 
                    placeholder="ex: {{__('slug-page')}}"
                    value="{{ old('slug') }}">
                @include('admin.components.error', ['errors' => $errors->get('slug')])
            </div>
            <div class="form-group">
                <label for="content">{{__('Content')}}</label>
                @include('admin.components.error', ['errors' => $errors->get('content')])
                <textarea class="form-control init-tinymce" id="content" name="content"  rows="3">
                    {{ old('content') }}                    
                </textarea>
            </div>
            <button type="submit" class="btn btn-primary">{{__('Submit')}}</button>
        </form>
    </div>
</div>
@endsection

@section('scripts')
@component('admin.components.scripts', [
    'loads' => [
        asset('/vendor/tinymce/tinymce.min.js'),
        asset('/js/admin/inittinymce.js'),
    ]
])
@endcomponent
@endsection

resources/views/admin/post/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col-md-12 mb-2">
        <a class="btn btn-secondary col-md-2" href="{{route('posts.index')}}">{{__('Back')}}</a>
    </div>
</div>
<div class="card">
    <div class="card-header">{{__('Edit Post')}}</div>

    <div class="card-body">
        <form action="{{route('posts.update', $post->id)}}" method="post">
            @csrf
            @method('put')
            <div class="form-group">
                <label for="{{__('Title')}}">{{__('Title')}}</label>
                <input type="hidden" name="id" value="{{$post->id}}">
                <input type="text" class="form-control" id="title" name="title" 
                    placeholder="ex: post title" 
                    value="{{ old('title') ?? $post->title }}">
                @include('admin.components.error', ['errors' => $errors->get('title')])
            </div>
            <div class="form-group">
                <label for="{{__('Slug')}}">{{__('Slug')}}</label>
                <input type="text" class="form-control" id="slug" name="slug" 
                    placeholder="ex: post-slug"
                    value="{{ old('slug') ?? $post->slug}}">
                @include('admin.components.error', ['errors' => $errors->get('slug')])
            </div>
            <div class="form-group">
                <label for="{{__('contents')}}">{{__('Content')}}</label>
                @include('admin.components.error', ['errors' => $errors->get('content')])
                <textarea class="form-control init-tinymce" id="content" name="content"  rows="5">
                    {{ old('content') ?? $post->content}}
                </textarea>
            </div>

            <button type="submit" class="btn btn-primary">{{__('Submit')}}</button>
        </form>
    </div>
</div>
@endsection

@section('scripts')
@component('admin.components.scripts', [
    'loads' => [
        asset('/vendor/tinymce/tinymce.min.js'),
        asset('/js/admin/inittinymce.js'),
    ]
])
@endcomponent
@endsection

resources/views/admin/post/index.blade.php
@extends('layouts.admin')

@section('content')
@include('admin.includes.alert')
<div class="row">
    <div class="col-md-12 mb-2">
        <a class="btn btn-primary col-md-2" href="{{route('posts.create')}}">{{__('Create post')}}</a>
    </div>
</div>
<div class="card">
    <div class="card-header">{{__('Post list')}}</div>

    <div class="card-body">
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th class="col-8">{{(__('Post'))}}</th>
                        <th colspan=2>{{ __('Action') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($posts as $post)
                    <tr>
                        <td class="col-8"><a href="{{route('posts.show', $post->id)}}">{{ $post->title }}</a></td>
                        <td class="col-2"><a href="{{route('posts.edit', $post->id)}}">{{ __('Edit') }}</a></td>
                        <td>
                            <delete-btn data-url="{{route('posts.destroy', $post->id)}}"
                                message="{{__('Are you sure?')}}"
                                title="{{__('Delete Page')}}"
                                confirm="{{__('Yes')}}"
                                cancel="{{__('Cancel')}}">
                            </delete-btn>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="3" class="text-center">{{ __('No Data') }}</td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
            {{ $posts->links() }}
        </div>
    </div>
</div>
@endsection

resources/views/admin/post/show.blade.php
@extends('layouts.admin')

@section('content')
@include('admin.includes.alert')
<div class="row">
    <div class="col-md-12 mb-2">
        <a class="btn btn-secondary col-md-2" href="{{route('posts.index')}}">{{__('Back')}}</a>
        <a class="btn btn-primary col-md-2" href="{{route('posts.edit', $post->id)}}">{{__('Edit')}}</a>
    </div>
</div>
<div class="card">
    <div class="card-header">{{__('Page Details')}}</div>
    <div class="card-body">
        <div>
            <label><b>{{__('Title')}}</b></label>
            <p>{{$post->title}}</p>
        </div>
        <div>
            <label><b>{{__('Slug')}}</b></label>
            <p>{{$post->slug}}</p>
        </div>
        <div>
            <label><b>{{__('Content')}}</b></label> 
            <div>{!!$post->content!!}</div>
        </div>
    </div>
</div>
@endsection