routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'PageController@homepage')->name('homepage');
Route::get('/contact-us', 'ContactController@form')->name('inquiry.form');
Route::post('/contact-us', 'ContactController@send')
    ->middleware('throttle:5')
    ->name('inquiry.send');

Route::get('/blog', 'PageController@blog')->name('blog.index');
Route::get('/blog/{post}', 'PageController@post')->name('blog.post');
Route::get('{page}', 'PageController@single')->name('single');

Route::prefix(config('admin.url'))->group(function () {
    Auth::routes();
    Route::middleware('auth')->group(function () {
        Route::get('/home', 'Admin\HomeController@index')->name('home');
        Route::resource('/posts', 'Admin\PostController');
        Route::resource('/pages', 'Admin\PageController');
        Route::resource('/menus', 'Admin\MenuController');
    });
});

app/Models/Menu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    protected $fillable = [
        'parent_id',
        'name',
        'url',
        'order',
    ];
    
    public function parent()
    {
        return $this->belongsTo('App\Models\Menu', 'parent_id');
    }

    public function childs()
    {
        return $this->hasMany('App\Models\Menu', 'parent_id');
    }

    public function scopeOnlyParent()
    {
        return $this->whereNull('parent_id');
    }
}

app/Http/Controllers/Admin/MenuController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Menu\StoreRequest;
use App\Http\Requests\Admin\Menu\UpdateRequest;
use App\Models\Menu;
use App\Services\WebConfig;
use App\Traits\ReturnTrait;
use Illuminate\Http\Request;

class MenuController extends Controller
{
    use ReturnTrait;

    public function index()
    {
        $menus = Menu::orderBy('order', 'asc')
            ->paginate(config('admin.menu.limit'));
        return view('admin.menu.index', compact('menus'));
    }

    public function create()
    {
        $parents = Menu::onlyParent()->get();
        return view('admin.menu.create', compact('parents'));
    }

    public function store(StoreRequest $request, WebConfig $config)
    {
        $menu = Menu::create($request->validated());
        $config->updateMenu();
        return redirect()->route('menus.show', $menu->id)
            ->with('success', __('New menu has been added'));
    }

    public function show(Menu $menu)
    {
        return view('admin.menu.show', compact('menu'));
    }

    public function edit(Menu $menu)
    {
        $parents = Menu::onlyParent()->get();
        return view('admin.menu.edit', compact('menu', 'parents'));
    }

    public function update(UpdateRequest $request, WebConfig $config, Menu $menu)
    {
        $menu->update($request->validated());
        $config->updateMenu();
        return redirect()->route('menus.show', $menu->id)
            ->with('success', __('New menu has been updated'));
    }

    public function destroy(Request $request, WebConfig $config, Menu $menu)
    {
        $menu->delete();
        $config->updateMenu();
        if ($request->expectsJson()) {
            return $this->returnExpectJson(
                ['status' => 'ok'],
                ['success' => __('Menu has been deleted')]
            );
        }
        return redirect()->route('menus.index')
            ->with('success', __('Menu has been deleted'));
    }
}

resources/views/admin/menu/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col-md-12 mb-2">
        <a class="btn btn-secondary col-md-2" href="{{route('menus.index')}}">{{__('Back')}}</a>
    </div>
</div>
<div class="card">
    <div class="card-header">{{__('Create menu')}}</div>
    <div class="card-body">
        <form action="{{route('menus.store')}}" method="post">
            @csrf
            <div class="form-group">
                <label for="name">{{__('Name')}}</label>
                <input type="text" class="form-control" id="name" name="name" />
                @include('admin.components.error', ['errors' => $errors->get('name')])
            </div>
            <div class="form-group">
                <label for="url">{{__('Url')}}</label>
                <input type="text" class="form-control" id="url" name="url" />
                @include('admin.components.error', ['errors' => $errors->get('url')])
            </div>
            <div class="form-group">
                <label for="order">{{__('Order')}}</label>
                <input type="number" min="0" class="form-control" id="order" name="order" />
                @include('admin.components.error', ['errors' => $errors->get('order')])
            </div>
            <div class="form-group">
                <label for="parent">{{__('Parent')}}</label>
                <select type="text" class="form-control" id="parent" name="parent">
                    <option value="">--no parent--</option>
                    @foreach ($parents as $parent)
                    <option value="{{$parent->id}}">{{$parent->name}}</option>
                    @endforeach
                </select>
                @include('admin.components.error', ['errors' => $errors->get('parent')])
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
@endsection

resources/views/admin/menu/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col-md-12 mb-2">
        <a class="btn btn-secondary col-md-2" href="{{route('menus.index')}}">{{__('Back')}}</a>
    </div>
</div>
<div class="card">
    <div class="card-header">{{__('Edit menu')}}</div>
    <div class="card-body">
        <form action="{{route('menus.update', $menu->id)}}" method="post">
            @csrf
            @method('put')
            <div class="form-group">
                <label for="name">{{__('Name')}}</label>
                <input type="text" class="form-control" id="name'" name="name" 
                    value="{{ old('name') ?? $menu->name }}"/>
                @include('admin.components.error', ['errors' => $errors->get('name')])
            </div>
            <div class="form-group">
                <label for="url">{{__('Url')}}</label>
                <input type="text" class="form-control" id="url" name="url" 
                    value="{{ old('url') ?? $menu->url }}"/>
                @include('admin.components.error', ['errors' => $errors->get('url')])
            </div>
            <div class="form-group">
                <label for="{{__('order')}}">{{__('Order')}}</label>
                <input type="number" min="0" class="form-control" id="{{__('order')}}" name="{{__('order')}}" 
                    value="{{ old('order') ?? $menu->order}}"/>
                @include('admin.components.error', ['errors' => $errors->get('order')])
            </div>
            <div class="form-group">
                <label for="{{__('parent')}}">{{__('Parent')}}</label>
                <select type="text" class="form-control" id="{{__('parent')}}" name="{{__('parent')}}">
                    <option value="">--no parent--</option>
                    @foreach ($parents as $parent)
                    <option {{$parent->id == $menu->parent_id ? 'selected' : '' }} value="{{$parent->id}}">
                        {{$parent->name}}
                    </option>
                    @endforeach
                </select>
                @include('admin.components.error', ['errors' => $errors->get('parent')])
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
@endsection

resources/views/admin/menu/index.blade.php
@extends('layouts.admin')

@section('content')
@include('admin.includes.alert')
<div class="row">
    <div class="col-md-12 mb-2">
        <a class="btn btn-primary col-md-2" href="{{route('menus.create')}}">{{__('Create menu')}}</a>
    </div>
</div>
<div class="card">
    <div class="card-header">{{__('Menu list')}}</div>

    <div class="card-body">
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th class="col-8">{{(__('Menu'))}}</th>
                        <th colspan=2>{{ __('Action') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($menus as $menu)
                    <tr>
                        <td class="col-8"><a href="{{route('menus.show', $menu->id)}}">{{ $menu->name }}</a></td>
                        <td class="col-2"><a href="{{route('menus.edit', $menu->id)}}">{{ __('Edit') }}</a></td>
                        <td>
                            <delete-btn data-url="{{route('menus.destroy', $menu->id)}}"
                                message="{{__('Are you sure?')}}"
                                title="{{__('Delete Menu')}}">
                            </delete-btn>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="3" class="text-center">{{ __('No Data') }}</td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
            {{ $menus->links() }}
        </div>
    </div>
</div>
@endsection

resources/views/admin/menu/show.blade.php
@extends('layouts.admin')

@section('content')
@include('admin.includes.alert')
<div class="row">
    <div class="col-md-12 mb-2">
        <a class="btn btn-secondary col-md-2" href="{{route('menus.index')}}">{{__('Back')}}</a>
        <a class="btn btn-primary col-md-2" href="{{route('menus.edit', $menu->id)}}">{{__('Edit')}}</a>
    </div>
</div>
<div class="card">
    <div class="card-header">{{__('Menu Details')}}</div>
    <div class="card-body">
        <div>
            <label><b>{{__('Name')}}</b></label>
            <p>{{$menu->name}}</p>
        </div>
        <div>
            <label><b>{{__('Url')}}</b></label>
            <p>{{$menu->url}}</p>
        </div>
        <div>
            <label><b>{{__('Order')}}</b></label>
            <p>{{$menu->order}}</p>
        </div>
    </div>
</div>
@endsection